mapping0 = {
    "oc dual-x": "unknown",
    "#1 computer": "unknown",
    "#11": "unknown",
    "#12 2-conductor with ground wire cable": "unknown",
    "#13": "unknown",
    "#2 computer": "unknown",
    "#6/#8": "unknown",
    "$16 holmes personal fans": "unknown",
    "$1600 laptop": "unknown",
    "$400 gpus": "unknown",
    "$400 rig": "unknown",
    "$500 pc": "unknown",
    "* .batstart batch:cgminer.exe": "unknown",
    "-qt client": "unknown",
    "-v -w256 -f0": "unknown",
    ".bat or .cmd files": "unknown",
    ".net 3.5 framework": "unknown",
    ".net 4 framework": "unknown",
    ".net framework": "unknown",
    ".net program widget thingie": "unknown",
    ".vbs script": "unknown",
    "/dev/ttyacm0": "unknown",
    "/etc/init.d/cgminer": "unknown",
    "/etc/x11... file": "unknown",
    "0 asic hashboard": "unknown",
    "0.5 and 1.0 thermal pads": "unknown",
    "0.5 bamt installation": "unknown",
    "0.75mm2 cables (21awg)": "unknown",
    "021d75d0": "unknown",
    "06 width: 64 bits clock: 33mhz": "unknown",
    "06748be7": "unknown",
    "08 macbook pro": "unknown",
    "08volts regulator": "unknown",
    "1 1050w psu": "unknown",
    "1 120v 20 amp": "unknown",
    "1 5870": "5870",
    "1 5970": "5970",
    "1 bfl sc 60": "bfl sc", # Closest match, assuming a typo or version difference.
    "1 board s9": "antminer s9", # Assuming the user refers to a single board from an S9 unit.
    "1 card": "unknown",
    "1 chip furies": "unknown", # No exact match, possibly referring to a product not listed.
    "1 corsair ax1200 (1200w 6(6p+2p)1 old 160gb sata hd": "unknown",
    "1 fan": "unknown",
    "1 gb ddr2": "unknown",
    "1 gb of video": "unknown",
    "1 gh/s": "unknown",
    "1 gig of ram": "unknown",
    "1 gpu thread": "unknown",
    "1 ground": "unknown",
    "1 hdd": "unknown",
}

mapping1 = {
    "1 megawatt town commercial license": "unknown",
    "1 pcie (6pin) connector": "unknown",
    "1 ph/s miner": "unknown",
    "1 phase 200 amp panel": "unknown",
    "1 pole breaker": "unknown",
    "1 pump": "unknown",
    "1 s7 (3.2 th/s)": "antminer s7",  # Assuming the specification is a hint to the model.
    "1 sappire 5850 xtreme": "5850",  # Assuming a typo in "sapphire".
    "1 single gpu card": "unknown",
    "1 ssd": "unknown",
    "1 th image": "unknown",
    "1 th/s dragonminer": "unknown",  # No exact match, but seems specific to a mining hardware.
    "1 th/s miner": "unknown",  # Too generic to map to a specific model.
    "1 ths sino sigma asic miner": "unknown",  # No matching entry.
    "1 watt per gh hardware": "unknown",
    "1\" gap": "unknown",
    "1-1 extender": "unknown",
    "1-4 shares": "unknown",
    "1->16x risers": "unknown",
    "1-x16 powered risers": "unknown",
    "1.1.8.0c": "unknown",
    "1.15d spartan 6 lx 90 board": "unknown",  # Specific to FPGA boards, but no exact match.
    "1.2 ghps rig": "unknown",
    "1.2 mh": "unknown",
    "1.2g hashes": "unknown",
    "1.2kw 48v wind turbine": "unknown",
    "1.2kw seasonic psu": "unknown",
    "1.2mw sub-distribution panel": "unknown",
    "1.3 mh": "unknown",
    "1.3t rig": "unknown",
    "1.5 image": "unknown",
    "1.5gh/s": "unknown",
    "1.5ghz netbook": "unknown",
    "1.5kw grid connected solar system": "unknown",
    "1.5tb drive": "unknown",
    "1.5tb drives": "unknown",
    "1.5th dragons": "unknown",  # Seems like a reference to a mining hardware, but no exact match.
    "1.5th of mining power": "unknown",
    "1.5th version": "unknown",
    "1.6 amp fan": "unknown",
    "1.6 th/s terraminer": "unknown",  # No exact match, but seems specific to a mining hardware.
    "1.61 phoenix": "unknown",
    "1.6ghz amd processor": "unknown",
    "1.6th miner": "unknown",
    "1.6th/s miner": "unknown",
    "1.7gh": "unknown",
    "1.7gh/s rig": "unknown",
    "1.7kw offgrid solar power setup": "unknown",
    "1.9 amd dual core": "unknown",
    "1.9gh": "unknown",
}

mapping2 = {
    "15ft cat6 cables": "unknown",
    "15gh gpu farm": "unknown",
    "15k rpm fans": "unknown",
    "15mmx15mm square 1mm copper shrims": "unknown",
    "15x2amp circuit breaker (220v)": "unknown",
    "16 awg psu cable": "unknown",
    "16 bitfury": "unknown", # Bitfury products are listed but not with this specific name.
    "16 bitfury h-cards": "unknown", # Bitfury products are listed but not with this specific name.
    "16 gb memory": "unknown",
    "16 gb sd card": "unknown",
    "16 gig ram": "unknown",
    "16 gigs of ram": "unknown",
    "16 hcards (25gh/card tested) on a single mboard": "unknown",
    "16 netgear port hub": "unknown",
    "16 pairs of screw down terminals": "unknown",
    "16 pin controller": "unknown",
    "16 pins v1.1 boards": "unknown",
    "16 port switch": "unknown",
    "16\" extract fans": "unknown",
    "16-16 extender": "unknown",
    "16->1x riser": "unknown",
    "16-x16 risers": "unknown",
    "160 asic crypto mining container": "unknown",
    "1600 w power supply": "unknown",
    "1600 watt 90gold atx psu": "unknown",
    "16000 cfm from the machines": "unknown",
    "1600t2 evga psu": "unknown",
    "1600w bitmain stock psu": "unknown", # Closest match would be to Bitmain's PSU offerings, but not listed specifically.
    "1600w bitmain's supply": "unknown", # Closest match would be to Bitmain's PSU offerings, but not listed specifically.
    "1600w lepa": "unknown",
    "1600w lepa gold 4 module": "unknown",
    "1600w lepa psu": "unknown",
    "1600w power supply from halong": "unknown",
    "1600w psu(s)": "unknown",
    "1600w rosewill psu": "unknown",
    "1600w sorcerer power supply": "unknown",
    "1600w sorcerer psu": "unknown",
    "1600w-rated bitmain psu": "unknown", # Closest match would be to Bitmain's PSU offerings, but not listed specifically.
    "160ths": "unknown",
    "16404": "unknown",
    "16a boards": "unknown",
    "16a sockets": "unknown",
    "16awg cables": "unknown",
    "16ga cable": "unknown",
    "16gb class 10 sd card": "unknown",
    "16gb flash drive": "unknown",
    "16gb g.skill ddr3 pc3-19200": "unknown",
    "16gb gentoo raspberry pi": "unknown",
    "16gb hp branded usb stick": "unknown",
    "16gb sd card": "unknown",
}

mapping3 = {
    "1.9th/s": "unknown",
    "1/2 or 1 watt ones with the thicker legs": "unknown",
    "1/2\" bolts": "unknown",
    "1/2\"x1/2\" l-angle stuff": "unknown",
    "1/2\"x1/2\" square aluminum tube": "unknown",
    "10 amp 12 volt bricks": "unknown",
    "10 amp iec cord": "unknown",
    "10 amp import ps": "unknown",
    "10 awg wire": "unknown",
    "10 barrels": "unknown",
    "10 coins": "unknown",
    "10 cubes server 32gb ram quad cpu xeon": "unknown",
    "10 gauge 4 conductor soow": "unknown",
    "10 gauge cables": "unknown",
    "10 inch fans": "unknown",
    "10 nf1s": "unknown",
    "10 pack switchers": "unknown",
    "10 pin connecting cables": "unknown",
    "10 port \"treefrog\" powered usb 2.0 hub (sku #hy-hb-8101)": "unknown",
    "10 port 3.0 hubs": "unknown",
    "10 port aluminum usb 3.0 hub": "unknown",
    "10 port metal anker hubs": "unknown",
    "10 port off brand hub": "unknown",
    "10 port powered hub (4a)": "unknown",
    "10 port powered usb 3.0": "unknown",
    "10 port usb 2.0 hub": "unknown",
    "10 port usb2.0 hubs": "unknown",
    "10 port usb3 4amp hub": "unknown",
    "10 ports usb hub": "unknown",
    "10 rigs with 4 cards each": "unknown",
    "10 way usb hub": "unknown",
    "10\" desk fan": "unknown",
    "10\" fan": "unknown",
    "10\" flex duct": "unknown",
    "10-2 romex copper": "unknown",
    "10-30r dryer outlet": "unknown",
    "10-port 3.5a hub": "unknown",
    "10-port gigabit switch": "unknown",
    "10-port hub": "unknown",
    "10.0 routers": "unknown",
    "10.11 drivers": "unknown",
    "10.3 models": "unknown",
    "10.7ghs blades": "unknown",
    "10.9": "unknown",
    "10/2 wg wire": "unknown",
    "10/3 power cable": "unknown",
    "100 amp box": "unknown",
    "100 amp panel": "unknown",
    "100 amp service 240v 6 outlets": "unknown",
    "100 amp sub panel": "unknown",
}

mapping4 = {
    "100 amp subpanel": "unknown",
    "100 amps in separate subpanel": "unknown",
    "100 computers": "unknown",
    "100 ghs miner": "unknown",  # No exact match, but could refer to a generic 100 GH/s capable miner
    "100 port switch": "unknown",
    "100% fresh install": "unknown",
    "100+mb/s wifi connection": "unknown",
    "1000 amp service": "unknown",
    "1000 asic miners": "unknown",
    "1000 ghs": "unknown",  # No exact match, but could refer to a generic 1000 GH/s capable miner
    "1000 gold": "unknown",
    "1000 mhash/sec": "unknown",  # No exact match, but could refer to a generic 1000 MH/s capable miner
    "1000 psu": "unknown",
    "1000 series": "unknown",
    "1000 w corsair hx 1000": "unknown",
    "1000 w power supply": "unknown",
    "1000 watt 80+ gold psu": "unknown",
    "1000 watt corsair": "unknown",
    "1000 watt inverter": "unknown",
    "1000 watt pc psu": "unknown",
    "1000 watt psu's": "unknown",
    "1000 watt psus": "unknown",
    "1000 watt raidmax psu": "unknown",
    "1000 watter psu": "unknown",
    "10000 btu window mount": "unknown",
    "1000ma psu": "unknown",
    "1000mh/s machine": "unknown",  # No exact match, but could refer to a generic 1000 MH/s capable miner
    "1000w": "unknown",
    "1000w atx psu": "unknown",
    "1000w chieftec": "unknown",
    "1000w cooler master silent pro psu": "unknown",
    "1000w dell server psu": "unknown",
    "1000w evga p2": "unknown",
    "1000w kingwin psu": "unknown",
    "1000w ocz": "unknown",
    "1000w rig": "unknown",
    "1000watt coolmaster silentprom psu": "unknown",
    "1000watt corsair 80 plus bronze psus": "unknown",
    "1000watt power supply": "unknown",
    "100a relays": "unknown",
    "100a sub panel": "unknown",
    "100a subpanel": "unknown",
    "100ah batteries": "unknown",
    "100amp box": "unknown",
    "100amp sub panel": "unknown",
    "100ft 14 guage wire": "unknown",
    "100gb ssd": "unknown",
    "100gh/s": "unknown",  # No exact match, but could refer to a generic 100 GH/s capable miner
    "100ghs hardwre": "unknown",  # No exact match, but could refer to a generic 100 GH/s capable miner
    "100ghz contract": "unknown"
}

mapping5 = {
    "100kw datacenter": "unknown",
    "100kwatt array": "unknown",
    "100m": "unknown",
    "100mh card": "unknown",
    "100mh/s boxes": "unknown",
    "100mhash": "unknown",
    "100th s19 pro": "antminer s19 pro",
    "100uf capacitor": "unknown",
    "100w exhaust fan": "unknown",
    "100x 1/4 watts": "unknown",
    "102ghs": "unknown",
    "1050 ti gpu": "unknown",  # No direct match, but related to graphics cards used in mining rigs.
    "1050 watts cooler master silent pro gold": "unknown",
    "1050gs": "unknown",
    "1050w 80+gold thermaltake": "unknown",
    "1050w cougar psu": "unknown",
    "105ph": "unknown",
    "1075w power supplys": "unknown",
    "1080": "unknown",  # Likely refers to Nvidia GTX 1080, but not listed.
    "1090 x6 cpu": "unknown",
    "10a 250v cables": "unknown",
    "10a 5x20 fuses": "unknown",
    "10a automotive fuse": "unknown",
    "10a fuse": "unknown",
    "10ga 2-cond automotive wire": "unknown",
    "10ga aluminum wire": "unknown",
    "10ga leads": "unknown",
    "10gb ram": "unknown",
    "10gh/s block erupter blade": "unknown",  # Close to "block erupter asics" but not listed.
    "10gh/s miner": "unknown",
    "10ghs cubes": "unknown",
    "10ghs on genesis mining": "unknown",
    "10k multiturn trimpots": "unknown",
    "10k smd 0603 resistors": "unknown",
    "10megabit switch": "unknown",
    "10ohm resistors": "unknown",
    "10x dual xeon 5630": "unknown",
    "10x nema outlets": "unknown",
    "11.04": "unknown",
    "11.04 iso cd": "unknown",
    "11.04 machines": "unknown",
    "11.04 ubuntu from usb stick": "unknown",
    "11.10 drivers": "unknown",
    "11.12 drivers": "unknown",
    "11.3": "unknown",
    "11.4 drivers": "unknown",
    "11.5": "unknown",
    "11.5 version of the ati driver": "unknown",
    "11.6": "unknown",
    "11.6 driver": "unknown",
}

mapping6 = {
    "11.6 drivers": "unknown",
    "11.7": "unknown",
    "11.7 driver": "unknown",
    "110 to 220 v step up converters": "unknown",
    "110 volt plug": "unknown",
    "1100 series": "unknown",
    "110gh/s mining rig": "unknown",
    "110gh/s r-boxes": "unknown",
    "110k stale shares": "unknown",
    "110kwatt array": "unknown",
    "110th": "unknown",
    "110th s19": "antminer s19", # Assuming a typo or version difference, closest match.
    "110v": "unknown",
    "110v ac wall": "unknown",
    "110w psu": "unknown",
    "112 3-phase 120v kva transformer": "unknown",
    "11221-02-40g": "unknown",
    "115 watt array": "unknown",
    "1150 cpu": "unknown",
    "115kwatt array": "unknown",
    "116 w gts450": "unknown",
    "1166 asic": "unknown",
    "1166 pro": "canaan avalonminer 1166 pro",
    "1166 pro 81 th/s": "canaan avalonminer 1166 pro", # Assuming a specification detail, closest match.
    "1166 pro75th miners": "canaan avalonminer 1166 pro", # Assuming a specification detail, closest match.
    "11_6 catalyst": "unknown",
    "11kv to 380v (3 phase) transformer": "unknown",
    "11ths units": "unknown",
    "12 5870s": "5870",
    "12 core xeon": "unknown",
    "12 gauge cables": "unknown",
    "12 inch fans": "unknown",
    "12 port switch": "unknown",
    "12 port usb powered hub": "unknown",
    "12 s1 antminers": "antminer s1",
    "12 sticks": "unknown",
    "12 v 160 ah gel battery": "unknown",
    "12 volt adapter": "unknown",
    "12 volt cable": "unknown",
    "12 volt power cables": "unknown",
    "12\" 1060cfm vortex fan": "unknown",
    "12\" duct": "unknown",
    "12\" exhaust hoses": "unknown",
    "12\" extenders": "unknown",
    "12\" flex duct": "unknown",
    "12\" hole": "unknown",
    "12-2 wire": "unknown",
    "12.1 + 2.1 sdk": "unknown",
    "12.1 driver": "unknown",
    "12.10": "unknown",
}

mapping7 = {
    "12.10 driver": "unknown",
    "12.7 beta driver": "unknown",
    "12.8 catalyst drivers": "unknown",
    "12.8 driver": "unknown",
    "12.8 drivers": "unknown",
    "12.93ths antminer": "unknown",  # Closest match would be an Antminer S9 variant, but none exactly match "12.93ths".
    "12/2 with ground wire cable": "unknown",
    "12/2 yellow romex": "unknown",
    "12/3 wire": "unknown",
    "120 amp 240v supply": "unknown",
    "120 amp fuse": "unknown",
    "120 amp hour batteries": "unknown",
    "120 and 240 line": "unknown",
    "120 in supersize with an l shaped piece below what would otherwise be thee round prong on a 120 plug": "unknown",
    "120 mm fans": "unknown",
    "120 scythe 1200 fans": "unknown",
    "120 systems in the tub": "unknown",
    "120 volt power": "unknown",
    "1200 hp server psu": "unknown",
    "1200 w psu": "unknown",
    "1200 watt antec power supply": "unknown",
    "1200 watt crossfire certified psu": "unknown",
    "1200 watt hp power supply": "unknown",
    "1200 watt nzxt psu": "unknown",
    "1200 watt psu": "unknown",
    "1200 watt psus": "unknown",
    "1200 watts psu": "unknown",
    "12000 cfm fan": "unknown",
    "1200w (60a+60a) thermaltake tr2 rx psu": "unknown",
    "1200w coolermaster gold": "unknown",
    "1200w coolermaster silent gold psu": "unknown",
    "1200w fsp": "unknown",
    "1200w platinum dps-1200fb-a": "unknown",
    "1200w power supply": "unknown",
    "1200w psus from amitylabs": "unknown",
    "1200watt antec": "unknown",
    "1200watt antec power supply": "unknown",
    "120cpu-s": "unknown",
    "120gb hdd": "unknown",
    "120gb ssd": "unknown",
    "120gig ssd ocz agility 3": "unknown",
    "120kh/s miner": "unknown",
    "120mm case fan": "unknown",
    "120mm dust shields": "unknown",
    "120mm fan intakes": "unknown",
    "120th s19": "unknown",  # Closest match would be an Antminer S19 variant, but none exactly match "120th".
    "120v 20a circuits": "unknown",
    "120v 30a circuits": "unknown",
    "120v 750w server power supply": "unknown",
    "120vac 20amp circuits": "unknown",
}

mapping8 = {
    "120w 12v power supply": "unknown",
    "120w psu": "unknown",
    "1246": "canaan avalonminer 1246",
    "1246 asic": "canaan avalonminer 1246",
    "1246-n-85t avalon": "canaan avalonminer 1246", # Assuming a specific model of 1246, but exact match not listed
    "125 amp sub panel": "unknown",
    "1250 ghash/s": "unknown",
    "1250 gold psu": "unknown",
    "1250 psu": "unknown",
    "1250w": "unknown",
    "1250w ocz": "unknown",
    "1250w ocz psu": "unknown",
    "1250w psu": "unknown",
    "1250w seasonic psu": "unknown",
    "1250w xfx psu": "unknown",
    "1250w zalman platinum": "unknown",
    "125a two pole circuit breaker": "unknown",
    "125amp panel": "unknown",
    "126 th/s miner": "unknown",
    "128 gb ssd": "unknown",
    "128 worksize": "unknown",
    "128gb card": "unknown",
    "128gb sd card": "unknown",
    "12awg cord": "unknown",
    "12awg power wire": "unknown",
    "12ga c20 to c13 cables": "unknown",
    "12gb ram": "unknown",
    "12gh/s miner": "unknown",
    "12guage wire": "unknown",
    "12in register": "unknown",
    "12m usb lead": "unknown",
    "12mm mdf": "unknown",
    "12port hubs": "unknown",
    "12v (yellow) cable": "unknown",
    "12v 30 amp power supply": "unknown",
    "12v 5 amps supply": "unknown",
    "12v 5a power supply": "unknown",
    "12v 65 amp 750 watt charge controller": "unknown",
    "12v batteries": "unknown",
    "12v cable": "unknown",
    "12v leisure batteries": "unknown",
    "12v pin": "unknown",
    "12v power pack": "unknown",
    "12v power supply": "unknown",
    "12v to 5v converter": "unknown",
    "12v3a usb 2.0 hub": "unknown",
    "13": "unknown",
    "13 gpu rig": "unknown",
    "13 pcs": "unknown",
    "13 port usb hub": "unknown",
}

mapping9 = {
    "13 units": "unknown",
    "13-inch aluminium late 2008": "unknown",
    "13-port powered usb hub": "unknown",
    "13.0 th": "unknown",
    "13.1": "unknown",
    "13.1 amd drivers": "unknown",
    "13.11 b9.4": "unknown",
    "13.11 cataclysm version+cgminer 2.11.4": "unknown",
    "13.12": "unknown",
    "13.5 and 14th s9s": "antminer s9",  # Assuming the user refers to both 13.5th and 14th versions of S9.
    "13.5 s9 december batch": "antminer s9",
    "13.5 th/s models": "antminer s9",  # Assuming the user refers to the S9 models around 13.5th.
    "13.5t": "antminer s9",  # Assuming the user refers to the S9 model with a hash rate around 13.5th.
    "13.5th s9": "antminer s9",
    "13.5th s9s": "antminer s9",
    "13.5th version": "antminer s9",  # Assuming the user refers to the S9 model.
    "13.6th machine": "unknown",
    "1300 evga g2": "unknown",
    "1300 supernova gold psu": "unknown",
    "1300 w rosewill psu": "unknown",
    "1300 watt evga g2 gold plus power supply": "unknown",
    "1300 watt evga gold": "unknown",
    "1300 watt power supply": "unknown",
    "1300 watt server power supply": "unknown",
    "1300cfm attic heat exhaust fan": "unknown",
    "1300w coolermaster gold": "unknown",
    "1300w evga gold psu": "unknown",
    "1300w evga supernovas": "unknown",
    "1300w psu(s)": "unknown",
    "13a wall socket a power cord": "unknown",
    "13th s9": "antminer s9",
    "13ths antminer": "antminer s9",  # Assuming the user refers to an S9 model with a hash rate around 13ths.
    "14": "unknown",
    "14 awg": "unknown",
    "14 gauge 5-15p cables": "unknown",
    "14 gauge pdu": "unknown",
    "14 gauge power cable": "unknown",
    "14 sticks": "unknown",
    "14-3 wire": "unknown",
    "14-30 dryer socket (30a 240v service)": "unknown",
    "14.5t": "unknown",
    "14/2 wire": "unknown",
    "140-120mm adapter": "unknown",
    "140-watt soldering guns": "unknown",
    "14000 btu ac": "unknown",
    "14000 btu air conditioner": "unknown",
    "1400w psu": "unknown",
    "140mm noctua industrial 3000rpm fan": "unknown",
    "1440rpm fan": "unknown",
    "1452gb": "unknown"
}

mapping10 = {
    "1475 power supply": "unknown",
    "14awg 5-15p -> c13 wires": "unknown",
    "14awg c-13 power cable": "unknown",
    "14awg cables": "unknown",
    "14awg power cable": "unknown",
    "14awg power extensions": "unknown",
    "14awg sjt": "unknown",
    "14cm fan": "unknown",
    "14ghs": "unknown",
    "14t": "unknown",
    "14tb from dec 2017": "unknown",
    "14th s9": "antminer s9", # Assuming "14th" refers to the hash rate, closest match.
    "14th units from dec": "unknown",
    "14th version": "unknown",
    "14th/s miner": "unknown",
    "14th/sec s9": "antminer s9", # Assuming "14th/sec" refers to the hash rate, closest match.
    "15 am circuit": "unknown",
    "15 amp 110v circuit": "unknown",
    "15 amp 1600w power supply (sorcerer's from canaan)": "unknown", # No exact match, possibly related to Canaan products but not listed.
    "15 amp breaker": "unknown",
    "15 amp outlets": "unknown",
    "15 fpgas": "unknown",
    "15 mtr ethernet cable": "unknown",
    "15 th/s farm": "unknown",
    "15+ year old microwave": "unknown",
    "150 amp 220 volt service": "unknown",
    "150 amp box": "unknown",
    "150 amp service": "unknown",
    "150 asic server farm": "unknown",
    "150 mh/s": "unknown",
    "150 th": "unknown",
    "150' line": "unknown",
    "1500 cfm attic fan": "unknown",
    "15000 btu air conditioner": "unknown",
    "1500va ups": "unknown",
    "1500w power supply": "unknown",
    "1500w powersupply": "unknown",
    "1500w psus": "unknown",
    "1500w silverstone psu": "unknown",
    "1500w thermaltake": "unknown",
    "150a sub panels": "unknown",
    "150gh/s": "unknown",
    "150th": "unknown",
    "150w12v panel": "unknown",
    "15a 110v circuits": "unknown",
    "15a 14 awg c14-c13 power cord": "unknown",
    "15a automotive fuse": "unknown",
    "15a breakers": "unknown",
    "15a charge controller": "unknown",
    "15amp cables": "unknown",
}


def map_hardware_to_table2(string):
    res = "not found"
    for i in range(0, 11):
        if string in globals()["mapping" + str(i)]:
            res = globals()["mapping" + str(i)][string]
            break
    return res